name: Telegram Notification

on:
  push:
    branches: [main]  # or whichever branch you want
  release:
    types: [published]  # Optional: only for releases

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Message
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="📦 New push to *${{ github.repository }}* on branch *${{ github.ref_name }}*\n📝 Commit: ${{ github.event.head_commit.message }}" \
          -d parse_mode=Markdown
